version: "2"

services:
  web:
    image: nginx:latest
    ports:
    - "8081:80" # expose container port 80 to host port 8081
    volumes:
      - ./code:/code
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    image: php:7-fpm
    volumes:
      - ./code:/code
#      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - code-network

networks:
  code-network:
      driver: bridge